# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#000000

# Main text color
theme[main_fg]=#f8f8f2

# Title color for boxes
theme[title]=#afff00

# Highlight color for keyboard shortcuts
theme[hi_fg]=#ff8d34

# Background color of selected item in processes box
theme[selected_bg]=#524549

# Foreground color of selected item in processes box
theme[selected_fg]=#ff8d34

# Color of inactive/disabled text
theme[inactive_fg]=#615250

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#afff00

# Background color of the percentage meters
theme[meter_bg]=#615250

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#afff00

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#6532ff
theme[mem_box]=#00ff00
theme[net_box]=#6532ff
theme[proc_box]=#afff00

# Box divider line and small boxes line color
theme[div_line]=#615250

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#afff00
theme[temp_mid]=#afff00
theme[temp_end]=#d70000

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#00ff00
theme[cpu_mid]=#afff00
theme[cpu_end]=#afff00

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#afff00
theme[free_mid]=#00ff00
theme[free_end]=#6532ff

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#afff00
theme[cached_mid]=#00ff00
theme[cached_end]=#6532ff

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#ffb86c
theme[available_mid]=#afff00
theme[available_end]=#d70000

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#47ef7d
theme[used_mid]=#5bd9f3
theme[used_end]=#6575ab

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#ffb86c
theme[download_mid]=#6532ff
theme[download_end]=#d70000

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#47ef7d
theme[upload_mid]=#5bd9f3
theme[upload_end]=#6575ab

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#00ff00
theme[process_mid]=#afff00
theme[process_end]=#afff00
