#!/usr/bin/env bash
#
# Scan, select, and connect to Wi-Fi networks using rofi with .rasi config
#
# Requirements:
# 	- nmcli (networkmanager)
# 	- rofi
# 	- notify-send (libnotify)
#
# Author: Jesse Mirabel <sejjymvm@gmail.com>
# Updated: December 09, 2025 - Converted to rofi .rasi theme
# License: MIT

RED='\033[1;31m'
RST='\033[0m'

TIMEOUT=5
RASI_THEME="./style-11.rasi"

ensure-enabled() {
	local radio
	radio=$(nmcli radio wifi)
	if [[ $radio == 'enabled' ]]; then
		return 0
	fi
	nmcli radio wifi on

	local i state
	for ((i = 1; i <= TIMEOUT; i++)); do
		printf '\rEnabling Wi-Fi... (%d/%d)' $i $TIMEOUT
		printf '\033[1A'

		state=$(nmcli -t -f STATE general)
		if [[ $state != 'connected (local only)' ]]; then
			break
		fi
		sleep 1
	done
	notify-send 'Wi-Fi Enabled' -i 'network-wireless-on' -r 1125
}

get-network-list() {
	nmcli device wifi rescan

	local i
	for ((i = 1; i <= TIMEOUT; i++)); do
		printf '\rScanning for networks... (%d/%d)' $i $TIMEOUT
		printf '\033[1A'

		list=$(timeout 1 nmcli device wifi list)
		networks=$(tail -n +2 <<< "$list" | awk '$2 != "--"')
		if [[ -n $networks ]]; then
			break
		fi
	done
	printf '\n%bScanning stopped.%b\n\n' "$RED" "$RST"

	if [[ -z $networks ]]; then
		notify-send 'Wi-Fi' 'No networks found' -i 'package-broken'
		return 1
	fi
}

select-network() {
	local header
	header=$(head -n 1 <<< "$list")

	# Use rofi with rasi theme instead of fzf
	bssid=$(echo "$networks" | rofi \
		-dmenu \
		-theme "$RASI_THEME" \
		-p "Wi-Fi Networks" \
		-mesg "$header" \
		-i \
		-lines 15 \
		-width 80 \
		| awk '{print $1}')

	if [[ -z $bssid ]]; then
		return 1
	fi
	if [[ $bssid == '*' ]]; then
		notify-send 'Wi-Fi' 'Already connected to this network' \
			-i 'package-install'
		return 1
	fi
}

connect-to-network() {
	printf 'Connecting...\n'
	if ! nmcli --ask device wifi connect "$bssid"; then
		notify-send 'Wi-Fi' 'Failed to connect' -i 'package-purge'
		return 1
	fi
	notify-send 'Wi-Fi' 'Successfully connected' -i 'package-install'
}

main() {
	tput civis
	ensure-enabled || exit 1
	get-network-list || exit 1
	tput cnorm
	select-network || exit 1
	connect-to-network || exit 1
}

main
